
spring:
  # jpa hibernate
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: false
        id:
          new_generator_mappings: false
      hbm2ddl:
        auto: false
  # redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379


# mysql database
datasource:
  hikari:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/common?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false